#include <arpa/inet.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <time.h>
#include <unistd.h>

int main(int argc, char *argv[]) {
	int simpleSocket, simplePort, returnStatus;
	struct sockaddr_in simpleServer;

	if(2 != argc) {
		fprintf(stderr, "\nUsage: %s <port>\n", argv[0]);
		exit(1);
	}

	simpleSocket = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);

	if(simpleSocket == -1) {
		fprintf(stderr, "\nError: could not create a socket.\n");
		exit(1);
	} else
		fprintf(stdout, "\nSocket created.\n");

	simplePort = atoi(argv[1]);

	memset(&simpleServer, '\0', sizeof(simpleServer)); 
	simpleServer.sin_family = AF_INET;
	simpleServer.sin_addr.s_addr = htonl(INADDR_ANY);
	simpleServer.sin_port = htons(simplePort);

	returnStatus = bind(simpleSocket, (struct sockaddr *)&simpleServer, sizeof(simpleServer));

	if(returnStatus == 0)
		fprintf(stdout, "Bind completed.\n");
	else {
		fprintf(stderr, "Error: could not bind to address.\n");
		close(simpleSocket);
		exit(1);
	}

	returnStatus = listen(simpleSocket, 5);

	if(returnStatus == -1) {
		fprintf(stderr, "Error: cannot listen on socket.\n");
		close(simpleSocket);
		exit(1);
	}

	char buffer[256];
	time_t ticks;
	struct sockaddr_in clientName = { 0 };
	int simpleChildSocket;
	unsigned int clientNameLength = sizeof(clientName);
	while(1) {
		fprintf(stdout, "\nWaiting for a connection...\n");
		simpleChildSocket = accept(simpleSocket, (struct sockaddr *)&clientName, &clientNameLength);

		if(simpleChildSocket == -1) {
			fprintf(stderr, "Cannot accept connections!\n");
			close(simpleSocket);
			exit(1);
		} else
			fprintf(stdout, "Connection established.\n");

		/* Il server calcola e invia la (sua) data, e l'ora, al client (esercizio II: dynamic answer). */

		ticks = time(NULL);
		snprintf(buffer, sizeof(buffer), "Hello UPO student!\nMessage generated by the server in date: %.24s\r\n", ctime(&ticks));

		write(simpleChildSocket, buffer, strlen(buffer));
		fprintf(stdout, "\nDate sent to client.\n");

		close(simpleChildSocket);
		fprintf(stdout, "\nConnection closed.\n");
	}

	close(simpleSocket);
	return 0;
}
